-- MySQL Script generated by MySQL Workbench
-- Wed Mar  4 22:06:19 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Library_Database
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Library_Database
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Library_Database` DEFAULT CHARACTER SET utf8 ;
USE `Library_Database` ;

-- -----------------------------------------------------
-- Table `Library_Database`.`book_types`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Library_Database`.`book_types` (
  `book_type_code` INT NOT NULL AUTO_INCREMENT,
  `book_type` VARCHAR(20) NULL,
  PRIMARY KEY (`book_type_code`),
  UNIQUE INDEX `language_UNIQUE` (`book_type` ASC) VISIBLE,
  UNIQUE INDEX `language_code_UNIQUE` (`book_type_code` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Library_Database`.`languages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Library_Database`.`languages` (
  `language_code` INT NOT NULL AUTO_INCREMENT,
  `language` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`language_code`),
  UNIQUE INDEX `language_UNIQUE` (`language` ASC) VISIBLE,
  UNIQUE INDEX `language_code_UNIQUE` (`language_code` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Library_Database`.`genres`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Library_Database`.`genres` (
  `genre_code` INT NOT NULL AUTO_INCREMENT,
  `genre` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`genre_code`),
  UNIQUE INDEX `genre_code_UNIQUE` (`genre_code` ASC) VISIBLE,
  UNIQUE INDEX `genre_UNIQUE` (`genre` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Library_Database`.`items`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Library_Database`.`items` (
  `item_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `available` INT NOT NULL,
  `on_hold` INT NOT NULL,
  `unavailable` INT NOT NULL,
  PRIMARY KEY (`item_id`),
  UNIQUE INDEX `item_id_UNIQUE` (`item_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Library_Database`.`books`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Library_Database`.`books` (
  `item_id` INT UNSIGNED NOT NULL,
  `book_type_code` INT NULL,
  `language_code` INT NULL,
  `genre_code` INT NULL,
  `summary` VARCHAR(1000) NULL,
  `publisher` VARCHAR(50) NULL,
  `shelf_number` INT NULL,
  `publication_date` DATE NULL,
  `title` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`item_id`),
  UNIQUE INDEX `item_id_UNIQUE` (`item_id` ASC) VISIBLE,
  INDEX `book_type_code_idx` (`book_type_code` ASC) VISIBLE,
  INDEX `language_code_idx` (`language_code` ASC) VISIBLE,
  INDEX `genre_code_idx` (`genre_code` ASC) VISIBLE,
  CONSTRAINT `book_type_code`
    FOREIGN KEY (`book_type_code`)
    REFERENCES `Library_Database`.`book_types` (`book_type_code`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `books_language_code`
    FOREIGN KEY (`language_code`)
    REFERENCES `Library_Database`.`languages` (`language_code`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `books_genre_code`
    FOREIGN KEY (`genre_code`)
    REFERENCES `Library_Database`.`genres` (`genre_code`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `books_item_id`
    FOREIGN KEY (`item_id`)
    REFERENCES `Library_Database`.`items` (`item_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Library_Database`.`authors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Library_Database`.`authors` (
  `author_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `item_id` INT UNSIGNED NOT NULL,
  `first_name` VARCHAR(30) NOT NULL,
  `last_name` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`author_id`),
  INDEX `item_id_idx` (`item_id` ASC) VISIBLE,
  CONSTRAINT `authors_item_id`
    FOREIGN KEY (`item_id`)
    REFERENCES `Library_Database`.`books` (`item_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Library_Database`.`periodical_types`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Library_Database`.`periodical_types` (
  `periodical_type_code` INT NOT NULL AUTO_INCREMENT,
  `periodical_type` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`periodical_type_code`),
  UNIQUE INDEX `language_UNIQUE` (`periodical_type` ASC) VISIBLE,
  UNIQUE INDEX `language_code_UNIQUE` (`periodical_type_code` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Library_Database`.`periodicals`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Library_Database`.`periodicals` (
  `item_id` INT UNSIGNED NOT NULL,
  `periodical_type_code` INT NULL,
  `language_code` INT NULL,
  `shelf_number` INT NULL,
  `genre_code` INT NULL,
  `publisher` VARCHAR(50) NULL,
  `publication_date` DATE NULL,
  `title` VARCHAR(45) NOT NULL,
  `summary` VARCHAR(1000) NULL,
  PRIMARY KEY (`item_id`),
  INDEX `periodical_type_code_idx` (`periodical_type_code` ASC) VISIBLE,
  INDEX `genre_code_idx` (`genre_code` ASC) VISIBLE,
  INDEX `language_code_idx` (`language_code` ASC) VISIBLE,
  UNIQUE INDEX `item_id_UNIQUE` (`item_id` ASC) VISIBLE,
  CONSTRAINT `periodical_type_code`
    FOREIGN KEY (`periodical_type_code`)
    REFERENCES `Library_Database`.`periodical_types` (`periodical_type_code`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `periodical_genre_code`
    FOREIGN KEY (`genre_code`)
    REFERENCES `Library_Database`.`genres` (`genre_code`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `periodical_language_code`
    FOREIGN KEY (`language_code`)
    REFERENCES `Library_Database`.`languages` (`language_code`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `periodical_item_id`
    FOREIGN KEY (`item_id`)
    REFERENCES `Library_Database`.`items` (`item_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Library_Database`.`audiovisual_media_types`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Library_Database`.`audiovisual_media_types` (
  `audiovisual_media_type_code` INT NOT NULL AUTO_INCREMENT,
  `audiovisual_media_type` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`audiovisual_media_type_code`),
  UNIQUE INDEX `language_UNIQUE` (`audiovisual_media_type` ASC) VISIBLE,
  UNIQUE INDEX `language_code_UNIQUE` (`audiovisual_media_type_code` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Library_Database`.`audiovisual_media`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Library_Database`.`audiovisual_media` (
  `item_id` INT UNSIGNED NOT NULL,
  `audiovisual_media_type_code` INT NULL,
  `language_code` INT NULL,
  `genre_code` INT NULL,
  `runtime` INT NULL,
  `summary` VARCHAR(1000) NULL,
  `publisher` VARCHAR(50) NULL,
  `publication_date` DATE NULL,
  `shelf_number` INT NULL,
  `title` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`item_id`),
  UNIQUE INDEX `item_id_UNIQUE` (`item_id` ASC) VISIBLE,
  INDEX `language_code_idx` (`language_code` ASC) VISIBLE,
  INDEX `genre_code_idx` (`genre_code` ASC) VISIBLE,
  INDEX `audiovisual_media_type_code_idx` (`audiovisual_media_type_code` ASC) VISIBLE,
  CONSTRAINT `audiovisual_media_genre_code`
    FOREIGN KEY (`genre_code`)
    REFERENCES `Library_Database`.`genres` (`genre_code`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `audiovisual_media_language_code`
    FOREIGN KEY (`language_code`)
    REFERENCES `Library_Database`.`languages` (`language_code`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `audiovisual_media_type_code`
    FOREIGN KEY (`audiovisual_media_type_code`)
    REFERENCES `Library_Database`.`audiovisual_media_types` (`audiovisual_media_type_code`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `audiovisual_media_item_id`
    FOREIGN KEY (`item_id`)
    REFERENCES `Library_Database`.`items` (`item_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Library_Database`.`contributors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Library_Database`.`contributors` (
  `contributor_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `item_id` INT UNSIGNED NOT NULL,
  `first_name` VARCHAR(30) NOT NULL,
  `last_name` VARCHAR(30) NOT NULL,
  `role` VARCHAR(20) NULL,
  PRIMARY KEY (`contributor_id`),
  INDEX `item_id_idx` (`item_id` ASC) VISIBLE,
  UNIQUE INDEX `contributor_id_UNIQUE` (`contributor_id` ASC) VISIBLE,
  UNIQUE INDEX `item_id_UNIQUE` (`item_id` ASC) VISIBLE,
  CONSTRAINT `contributors_item_id`
    FOREIGN KEY (`item_id`)
    REFERENCES `Library_Database`.`audiovisual_media` (`item_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Library_Database`.`equipment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Library_Database`.`equipment` (
  `item_id` INT UNSIGNED NOT NULL,
  `equipment_name` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`item_id`),
  UNIQUE INDEX `item_id_UNIQUE` (`item_id` ASC) VISIBLE,
  CONSTRAINT `equipment_item_id`
    FOREIGN KEY (`item_id`)
    REFERENCES `Library_Database`.`items` (`item_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Library_Database`.`patron_roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Library_Database`.`patron_roles` (
  `patron_role_code` INT NOT NULL,
  `patron_role` VARCHAR(15) NOT NULL,
  `loan_period` INT NOT NULL,
  `fine` FLOAT NOT NULL,
  PRIMARY KEY (`patron_role_code`),
  UNIQUE INDEX `staff_role_UNIQUE` (`patron_role` ASC) VISIBLE,
  UNIQUE INDEX `staff_role_code_UNIQUE` (`patron_role_code` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Library_Database`.`patrons`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Library_Database`.`patrons` (
  `patron_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `patron_role_code` INT NOT NULL,
  `first_name` VARCHAR(20) NOT NULL,
  `last_name` VARCHAR(20) NOT NULL,
  `date_of_birth` DATE NULL,
  `email` VARCHAR(40) NOT NULL,
  `password_hash` VARCHAR(255) NOT NULL,
  `is_active` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`patron_id`),
  UNIQUE INDEX `patron_id_UNIQUE` (`patron_id` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  INDEX `patron_role_code_idx` (`patron_role_code` ASC) VISIBLE,
  CONSTRAINT `patron_role_code`
    FOREIGN KEY (`patron_role_code`)
    REFERENCES `Library_Database`.`patron_roles` (`patron_role_code`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Library_Database`.`staff_roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Library_Database`.`staff_roles` (
  `staff_role_code` INT NOT NULL,
  `staff_role` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`staff_role_code`),
  UNIQUE INDEX `staff_role_UNIQUE` (`staff_role` ASC) VISIBLE,
  UNIQUE INDEX `staff_role_code_UNIQUE` (`staff_role_code` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Library_Database`.`staff`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Library_Database`.`staff` (
  `staff_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `staff_role_code` INT NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `first_name` VARCHAR(20) NOT NULL,
  `last_name` VARCHAR(20) NOT NULL,
  `date_of_birth` DATE NOT NULL,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  `phone_number` VARCHAR(10) NULL,
  `address` VARCHAR(100) NOT NULL,
  `password_hash` VARCHAR(255) NOT NULL,
  `is_active` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`staff_id`),
  INDEX `staff_role_code_idx` (`staff_role_code` ASC) VISIBLE,
  CONSTRAINT `staff_role_code`
    FOREIGN KEY (`staff_role_code`)
    REFERENCES `Library_Database`.`staff_roles` (`staff_role_code`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Library_Database`.`fines`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Library_Database`.`fines` (
  `fine_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `patron_id` INT UNSIGNED NOT NULL,
  `fine_amount` FLOAT NOT NULL,
  `fine_date` DATE NOT NULL,
  `paid_date` DATE NULL,
  `waived_date` DATE NULL,
  PRIMARY KEY (`fine_id`),
  UNIQUE INDEX `fine_id_UNIQUE` (`fine_id` ASC) VISIBLE,
  INDEX `patron_id_idx` (`patron_id` ASC) VISIBLE,
  CONSTRAINT `fines_patron_id`
    FOREIGN KEY (`patron_id`)
    REFERENCES `Library_Database`.`patrons` (`patron_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Library_Database`.`loan_statuses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Library_Database`.`loan_statuses` (
  `loan_status_code` INT NOT NULL AUTO_INCREMENT,
  `loan_status_name` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`loan_status_code`),
  UNIQUE INDEX `loan_status_code_UNIQUE` (`loan_status_code` ASC) VISIBLE,
  UNIQUE INDEX `loan_status_name_UNIQUE` (`loan_status_name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Library_Database`.`loans`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Library_Database`.`loans` (
  `loan_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `item_id` INT UNSIGNED NOT NULL,
  `patron_id` INT UNSIGNED NOT NULL,
  `loan_origin_date` DATE NOT NULL,
  `loan_due_date` DATE NOT NULL,
  `patron_role_code` INT NOT NULL,
  `loan_status_code` INT NOT NULL,
  PRIMARY KEY (`loan_id`),
  INDEX `item_id_idx` (`item_id` ASC) VISIBLE,
  INDEX `patron_id_idx` (`patron_id` ASC) VISIBLE,
  INDEX `patron_code_idx` (`patron_role_code` ASC) VISIBLE,
  INDEX `loan_status_code_idx` (`loan_status_code` ASC) VISIBLE,
  CONSTRAINT `loans_patron_id`
    FOREIGN KEY (`patron_id`)
    REFERENCES `Library_Database`.`patrons` (`patron_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `loans_patron_code`
    FOREIGN KEY (`patron_role_code`)
    REFERENCES `Library_Database`.`patron_roles` (`patron_role_code`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `loans_item_id`
    FOREIGN KEY (`item_id`)
    REFERENCES `Library_Database`.`items` (`item_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `loan_status_code`
    FOREIGN KEY (`loan_status_code`)
    REFERENCES `Library_Database`.`loan_statuses` (`loan_status_code`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE
)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `Library_Database`.`hold_statuses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Library_Database`.`hold_statuses` (
  `hold_status_code` INT NOT NULL,
  `hold_status_name` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`hold_status_code`),
  UNIQUE INDEX `hold_status_name_UNIQUE` (`hold_status_name` ASC) VISIBLE,
  UNIQUE INDEX `hold_status_code_UNIQUE` (`hold_status_code` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Library_Database`.`holds`
-- -----------------------------------------------------


CREATE TABLE IF NOT EXISTS `Library_Database`.`holds` (
  `hold_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `item_id` INT UNSIGNED NOT NULL,
  `patron_id` INT UNSIGNED NOT NULL,
  `hold_origin_date` DATE NOT NULL,
  `hold_expiration_date` DATE NOT NULL,
  `hold_status_code` INT NOT NULL,
  PRIMARY KEY (`hold_id`),
  INDEX `item_id_idx` (`item_id` ASC) VISIBLE,
  INDEX `patron_id_idx` (`patron_id` ASC) VISIBLE,
  INDEX `hold_status_code_idx` (`hold_status_code` ASC) VISIBLE,
  CONSTRAINT `holds_patron_id`
    FOREIGN KEY (`patron_id`)
    REFERENCES `Library_Database`.`patrons` (`patron_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `holds_item_id`
    FOREIGN KEY (`item_id`)
    REFERENCES `Library_Database`.`items` (`item_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `hold_status_code`
    FOREIGN KEY (`hold_status_code`)
    REFERENCES `Library_Database`.`hold_statuses` (`hold_status_code`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE
)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;



-- -----------------------------------------------------
-- Table `Library_Database`.`staff_signup_codes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Library_Database`.`staff_signup_codes` (
  `code_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `signup_code` VARCHAR(50) NOT NULL,
  `staff_role_code` INT NOT NULL,
  `created_by_admin_id` INT UNSIGNED NULL,
  `is_used` TINYINT(1) NOT NULL DEFAULT 0,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`code_id`),
  UNIQUE INDEX `signup_code_UNIQUE` (`signup_code` ASC) VISIBLE,
  INDEX `staff_role_code_idx` (`staff_role_code` ASC) VISIBLE,
  INDEX `created_by_admin_id_idx` (`created_by_admin_id` ASC) VISIBLE,
  CONSTRAINT `signup_codes_staff_role_code`
    FOREIGN KEY (`staff_role_code`)
    REFERENCES `Library_Database`.`staff_roles` (`staff_role_code`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `signup_codes_admin_id`
    FOREIGN KEY (`created_by_admin_id`)
    REFERENCES `Library_Database`.`staff` (`staff_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE
)
ENGINE = InnoDB;



ALTER TABLE fines
ADD COLUMN loan_id INT UNSIGNED NULL;

ALTER TABLE fines
ADD COLUMN paid_amount FLOAT NOT NULL DEFAULT 0;


-- -----------------------------------------------------
-- Triggers
-- -----------------------------------------------------
DROP TRIGGER IF EXISTS validate_loan_dates_before_insert;
DROP TRIGGER IF EXISTS validate_fines_before_update;

DELIMITER $$

CREATE TRIGGER validate_loan_dates_before_insert
BEFORE INSERT ON loans
FOR EACH ROW
BEGIN
  IF NEW.loan_due_date < NEW.loan_origin_date THEN
    SIGNAL SQLSTATE '45000'
      SET MESSAGE_TEXT = 'loan_due_date cannot be earlier than loan_origin_date.';
  END IF;
END$$

CREATE TRIGGER validate_fines_before_update
BEFORE UPDATE ON fines
FOR EACH ROW
BEGIN
  IF NEW.paid_date IS NOT NULL AND NEW.paid_date < NEW.fine_date THEN
    SIGNAL SQLSTATE '45000'
      SET MESSAGE_TEXT = 'paid_date cannot be earlier than fine_date.';
  END IF;

  IF NEW.waived_date IS NOT NULL AND NEW.waived_date < NEW.fine_date THEN
    SIGNAL SQLSTATE '45000'
      SET MESSAGE_TEXT = 'waived_date cannot be earlier than fine_date.';
  END IF;

  IF NEW.paid_amount < 0 THEN
    SIGNAL SQLSTATE '45000'
      SET MESSAGE_TEXT = 'paid_amount cannot be negative.';
  END IF;

  IF NEW.paid_amount > NEW.fine_amount THEN
    SIGNAL SQLSTATE '45000'
      SET MESSAGE_TEXT = 'paid_amount cannot exceed fine_amount.';
  END IF;
END$$

DELIMITER ;

-- adding return_date to loans table
ALTER TABLE loans
ADD COLUMN return_date DATE NULL AFTER loan_due_date;

-- setting return_date to loan_due_date for all loans with loan_status_code = 2 (returned)
UPDATE loans
SET return_date = loan_due_date
WHERE loan_status_code = 2;

--
INSERT INTO loan_statuses (loan_status_name)
VALUES ('Lost');

CREATE TABLE activity_logs (
  activity_id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  actor_type ENUM('patron','staff','system') NOT NULL,
  actor_id INT UNSIGNED NOT NULL,
  action_type VARCHAR(50) NOT NULL,
  item_id INT UNSIGNED NULL,
  loan_id INT UNSIGNED NULL,
  hold_id INT UNSIGNED NULL,
  fine_id INT UNSIGNED NULL,
  target_patron_id INT UNSIGNED NULL,
  description VARCHAR(255),
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE items
ADD COLUMN is_removed TINYINT(1) NOT NULL DEFAULT 0,
ADD COLUMN removed_reason VARCHAR(50) NULL,
ADD COLUMN removed_date DATETIME NULL;

ALTER TABLE books
ADD COLUMN cover_image_url VARCHAR(2048) NULL AFTER title;

ALTER TABLE periodicals
ADD COLUMN cover_image_url VARCHAR(2048) NULL AFTER title;

ALTER TABLE audiovisual_media
ADD COLUMN cover_image_url VARCHAR(2048) NULL AFTER title;

INSERT INTO loan_statuses (loan_status_name) VALUES ('Found');
INSERT INTO loan_statuses (loan_status_name) VALUES ('Deleted');

-- =====================================================
-- NOTIFICATIONS TABLE
-- =====================================================
CREATE TABLE IF NOT EXISTS `Library_Database`.`notifications` (
  `notification_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `patron_id` INT UNSIGNED NOT NULL,
  `notification_type` VARCHAR(50) NOT NULL,
  `message` VARCHAR(500) NOT NULL,
  `is_read` TINYINT(1) NOT NULL DEFAULT 0,
  `link_data` JSON NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`notification_id`),
  INDEX `patron_id_idx` (`patron_id` ASC) VISIBLE,
  INDEX `is_read_idx` (`is_read` ASC) VISIBLE,
  CONSTRAINT `notifications_patron_id`
    FOREIGN KEY (`patron_id`)
    REFERENCES `Library_Database`.`patrons` (`patron_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE
)
ENGINE = InnoDB;

-- =====================================================
-- TRIGGERS FOR NOTIFICATIONS
-- =====================================================

-- Trigger 1: Notify patron when their hold is ready for pickup
DELIMITER $$

DROP TRIGGER IF EXISTS notify_hold_ready$$

CREATE TRIGGER notify_hold_ready
AFTER UPDATE ON holds
FOR EACH ROW
BEGIN
  IF OLD.hold_status_code != 2 AND NEW.hold_status_code = 2 THEN
    INSERT INTO notifications (patron_id, notification_type, message, link_data)
    VALUES (NEW.patron_id, 'HOLD_READY', 
            CONCAT('Your hold is ready for pickup!'),
            JSON_OBJECT('hold_id', NEW.hold_id, 'item_id', NEW.item_id));
    
    -- Log the activity
    INSERT INTO activity_logs (actor_type, actor_id, action_type, hold_id, description, created_at)
    VALUES ('staff', IFNULL(@current_staff_id, 0), 'HOLD_READY_NOTIFICATION', NEW.hold_id, 
            CONCAT('Notification sent to patron ', NEW.patron_id), NOW());
  END IF;
END$$

-- Trigger 2: Notify patron when item is returned (for pending holds)
DROP TRIGGER IF EXISTS notify_on_return$$

CREATE TRIGGER notify_on_return
AFTER UPDATE ON loans
FOR EACH ROW
BEGIN
  DECLARE next_patron_id INT UNSIGNED;
  
  IF OLD.loan_status_code != 2 AND NEW.loan_status_code = 2 THEN
    -- Update item availability
    UPDATE items 
    SET available = available + 1
    WHERE item_id = NEW.item_id;
    
    -- Find next person with active hold
    SELECT patron_id INTO next_patron_id
    FROM holds
    WHERE item_id = NEW.item_id AND hold_status_code = 1
    ORDER BY hold_origin_date ASC LIMIT 1;
    
    -- Notify them
    IF next_patron_id IS NOT NULL THEN
      INSERT INTO notifications (patron_id, notification_type, message, link_data)
      VALUES (next_patron_id, 'ITEM_AVAILABLE', 
              CONCAT('An item you have on hold is now available for pickup!'),
              JSON_OBJECT('item_id', NEW.item_id));
      
      -- Update hold status to ready
      UPDATE holds
      SET hold_status_code = 2
      WHERE item_id = NEW.item_id AND hold_status_code = 1
      ORDER BY hold_origin_date ASC LIMIT 1;
    END IF;
    
    -- Log the activity
    INSERT INTO activity_logs (actor_type, actor_id, action_type, loan_id, item_id, description, created_at)
    VALUES ('patron', NEW.patron_id, 'ITEM_RETURNED', NEW.loan_id, NEW.item_id, 
            CONCAT('Item returned. Next hold notified: ', IFNULL(next_patron_id, 'none')), NOW());
  END IF;
END$$

-- Trigger 3: Notify patron when a fine is created
DROP TRIGGER IF EXISTS notify_fine_created$$

CREATE TRIGGER notify_fine_created
AFTER INSERT ON fines
FOR EACH ROW
BEGIN
  INSERT INTO notifications (patron_id, notification_type, message, link_data)
  VALUES (NEW.patron_id, 'FINE_CREATED', 
          CONCAT('A fine of $', NEW.fine_amount, ' has been applied to your account.'),
          JSON_OBJECT('fine_id', NEW.fine_id, 'amount', NEW.fine_amount));
  
  -- Log the activity
  INSERT INTO activity_logs (actor_type, actor_id, action_type, fine_id, target_patron_id, description, created_at)
  VALUES ('system', 0, 'FINE_NOTIFICATION', NEW.fine_id, NEW.patron_id, 
          CONCAT('Fine notification created: $', NEW.fine_amount), NOW());
END$$

-- Trigger 4: Notify patron when a fine is paid
DROP TRIGGER IF EXISTS notify_fine_paid$$

CREATE TRIGGER notify_fine_paid
AFTER UPDATE ON fines
FOR EACH ROW
BEGIN
  IF OLD.paid_date IS NULL AND NEW.paid_date IS NOT NULL THEN
    INSERT INTO notifications (patron_id, notification_type, message, link_data)
    VALUES (NEW.patron_id, 'FINE_PAID', 
            CONCAT('Your fine of $', NEW.fine_amount, ' has been recorded as paid. Thank you!'),
            JSON_OBJECT('fine_id', NEW.fine_id));
    
    -- Log the activity
    INSERT INTO activity_logs (actor_type, actor_id, action_type, fine_id, target_patron_id, description, created_at)
    VALUES ('staff', IFNULL(@current_staff_id, 0), 'FINE_PAID_NOTIFICATION', NEW.fine_id, NEW.patron_id, 
            CONCAT('Fine payment notification sent for $', NEW.paid_amount), NOW());
  END IF;
END$$

-- Trigger 5: Notify patron when loan is approaching due date (requires stored procedure call)
DROP TRIGGER IF EXISTS notify_overdue$$

CREATE TRIGGER notify_overdue
AFTER UPDATE ON loans
FOR EACH ROW
BEGIN
  IF NEW.loan_status_code = 1 AND NEW.loan_due_date = CURDATE() THEN
    INSERT INTO notifications (patron_id, notification_type, message, link_data)
    VALUES (NEW.patron_id, 'LOAN_DUE_SOON', 
            'Your library item is due today! Please return it to avoid fines.',
            JSON_OBJECT('loan_id', NEW.loan_id, 'item_id', NEW.item_id));
    
    -- Log the activity
    INSERT INTO activity_logs (actor_type, actor_id, action_type, loan_id, target_patron_id, description, created_at)
    VALUES ('system', 0, 'OVERDUE_NOTIFICATION', NEW.loan_id, NEW.patron_id, 
            'Due date reminder notification created', NOW());
  END IF;
END$$

-- Trigger 6: Notify patron when item is placed on hold
DROP TRIGGER IF EXISTS notify_hold_created$$

CREATE TRIGGER notify_hold_created
AFTER INSERT ON holds
FOR EACH ROW
BEGIN
  INSERT INTO notifications (patron_id, notification_type, message, link_data)
  VALUES (NEW.patron_id, 'HOLD_CREATED', 
          'Your hold request has been confirmed. We will notify you when the item is available.',
          JSON_OBJECT('hold_id', NEW.hold_id, 'item_id', NEW.item_id));
  
  -- Log the activity
  INSERT INTO activity_logs (actor_type, actor_id, action_type, hold_id, target_patron_id, description, created_at)
  VALUES ('patron', NEW.patron_id, 'HOLD_PLACED', NEW.hold_id, NEW.patron_id, 
          'Hold placed and notification created', NOW());
END$$

-- Trigger 7: Charge overdue fine when item is returned late
DROP TRIGGER IF EXISTS charge_overdue_fine$$

CREATE TRIGGER charge_overdue_fine
AFTER UPDATE ON loans
FOR EACH ROW
BEGIN
  DECLARE days_late INT;
  DECLARE daily_fine_amount FLOAT;
  DECLARE total_fine_amount FLOAT;
  DECLARE patron_role INT;
  
  -- Only process if return_date is being set and it's after due date
  IF NEW.return_date IS NOT NULL AND OLD.return_date IS NULL AND NEW.return_date > NEW.loan_due_date THEN
    -- Calculate days late
    SET days_late = DATEDIFF(NEW.return_date, NEW.loan_due_date);
    
    -- Get patron's daily fine amount from their role
    SELECT pr.fine INTO daily_fine_amount
    FROM patron_roles pr
    WHERE pr.patron_role_code = NEW.patron_role_code
    LIMIT 1;
    
    -- Calculate total fine
    SET total_fine_amount = days_late * IFNULL(daily_fine_amount, 0);
    
    -- Only create fine if there is an amount due
    IF total_fine_amount > 0 THEN
      -- Create fine record
      INSERT INTO fines (patron_id, fine_amount, fine_date, loan_id, paid_amount)
      VALUES (NEW.patron_id, total_fine_amount, CURDATE(), NEW.loan_id, 0);
      
      -- Log the activity
      INSERT INTO activity_logs (actor_type, actor_id, action_type, loan_id, item_id, description, created_at)
      VALUES ('system', 0, 'OVERDUE_FINE_CHARGED', NEW.loan_id, NEW.item_id, 
              CONCAT('Overdue fine: ', days_late, ' days late @ $', daily_fine_amount, '/day = $', total_fine_amount), NOW());
    END IF;
  END IF;
END$$

-- Trigger 8: Enhanced fine notification with late fee details
DROP TRIGGER IF EXISTS notify_fine_created_enhanced$$

CREATE TRIGGER notify_fine_created_enhanced
AFTER INSERT ON fines
FOR EACH ROW
BEGIN
  DECLARE days_late INT;
  DECLARE daily_fine_amount FLOAT;
  DECLARE notification_msg VARCHAR(500);
  DECLARE notification_type VARCHAR(50);
  
  -- Check if this is an overdue fine (has loan_id)
  IF NEW.loan_id IS NOT NULL THEN
    -- Get loan details for calculation
    SELECT 
      DATEDIFF(l.return_date, l.loan_due_date),
      pr.fine
    INTO days_late, daily_fine_amount
    FROM loans l
    JOIN patron_roles pr ON pr.patron_role_code = l.patron_role_code
    WHERE l.loan_id = NEW.loan_id
    LIMIT 1;
    
    -- Create detailed overdue notification
    SET notification_type = 'OVERDUE_FINE';
    SET notification_msg = CONCAT(
      'Late return fee: You were charged $', ROUND(daily_fine_amount, 2), 
      ' per day for ', IFNULL(days_late, 0), ' day(s) late. ',
      'Total amount due: $', ROUND(NEW.fine_amount, 2)
    );
  ELSE
    -- Regular fine (not overdue-related)
    SET notification_type = 'FINE_CREATED';
    SET notification_msg = CONCAT(
      'A fine of $', ROUND(NEW.fine_amount, 2), ' has been applied to your account.'
    );
  END IF;
  
  -- Create notification
  INSERT INTO notifications (patron_id, notification_type, message, link_data)
  VALUES (NEW.patron_id, notification_type, notification_msg,
          JSON_OBJECT('fine_id', NEW.fine_id, 'amount', NEW.fine_amount, 'loan_id', NEW.loan_id));
  
  -- Log the activity
  INSERT INTO activity_logs (actor_type, actor_id, action_type, fine_id, target_patron_id, description, created_at)
  VALUES ('system', 0, 'FINE_NOTIFICATION', NEW.fine_id, NEW.patron_id, 
          notification_msg, NOW());
END$$

-- Remove the old simple fine notification trigger since we have the enhanced one
DROP TRIGGER IF EXISTS notify_fine_created$$

DELIMITER ;
