-- MySQL Script generated by MySQL Workbench
-- Tue Mar  3 10:09:28 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Library_Database
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Library_Database
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Library_Database` DEFAULT CHARACTER SET utf8 ;
USE `Library_Database` ;

-- -----------------------------------------------------
-- Table `Library_Database`.`book_types`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Library_Database`.`book_types` (
  `book_type_code` INT NOT NULL AUTO_INCREMENT,
  `book_type` VARCHAR(20) NULL,
  PRIMARY KEY (`book_type_code`),
  UNIQUE INDEX `language_UNIQUE` (`book_type` ASC) VISIBLE,
  UNIQUE INDEX `language_code_UNIQUE` (`book_type_code` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Library_Database`.`languages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Library_Database`.`languages` (
  `language_code` INT NOT NULL AUTO_INCREMENT,
  `language` VARCHAR(20) NULL,
  PRIMARY KEY (`language_code`),
  UNIQUE INDEX `language_UNIQUE` (`language` ASC) VISIBLE,
  UNIQUE INDEX `language_code_UNIQUE` (`language_code` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Library_Database`.`genres`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Library_Database`.`genres` (
  `genre_code` INT NOT NULL AUTO_INCREMENT,
  `genre` VARCHAR(20) NULL,
  PRIMARY KEY (`genre_code`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Library_Database`.`books`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Library_Database`.`books` (
  `book_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `shelf_number` INT NULL,
  `available` INT NULL,
  `on_hold` INT NULL,
  `unavailable` INT NULL,
  `book_type_code` INT NULL,
  `language_code` INT NULL,
  `genre_code` INT NULL,
  `summary` VARCHAR(1000) NULL,
  `publisher` VARCHAR(50) NULL,
  `publication_date` DATE NULL,
  `title` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`book_id`),
  UNIQUE INDEX `book_id_UNIQUE` (`book_id` ASC) VISIBLE,
  INDEX `book_type_code_idx` (`book_type_code` ASC) VISIBLE,
  INDEX `language_code_idx` (`language_code` ASC) VISIBLE,
  INDEX `genre_code_idx` (`genre_code` ASC) VISIBLE,
  CONSTRAINT `book_type_code`
    FOREIGN KEY (`book_type_code`)
    REFERENCES `Library_Database`.`book_types` (`book_type_code`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `language_code`
    FOREIGN KEY (`language_code`)
    REFERENCES `Library_Database`.`languages` (`language_code`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `genre_code`
    FOREIGN KEY (`genre_code`)
    REFERENCES `Library_Database`.`genres` (`genre_code`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Library_Database`.`authors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Library_Database`.`authors` (
  `author_id` INT UNSIGNED NOT NULL,
  `book_id` INT UNSIGNED NOT NULL,
  `first_name` VARCHAR(20) NOT NULL,
  `last_name` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`author_id`, `book_id`),
  INDEX `book_id_idx` (`book_id` ASC) VISIBLE,
  CONSTRAINT `book_id`
    FOREIGN KEY (`book_id`)
    REFERENCES `Library_Database`.`books` (`book_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Library_Database`.`periodical_types`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Library_Database`.`periodical_types` (
  `periodical_type_code` INT NOT NULL AUTO_INCREMENT,
  `periodical_type` VARCHAR(20) NULL,
  PRIMARY KEY (`periodical_type_code`),
  UNIQUE INDEX `language_UNIQUE` (`periodical_type` ASC) VISIBLE,
  UNIQUE INDEX `language_code_UNIQUE` (`periodical_type_code` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Library_Database`.`periodicals`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Library_Database`.`periodicals` (
  `periodical_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `shelf_number` INT NULL,
  `available` INT NULL,
  `on_hold` INT NULL,
  `unavailable` INT NULL,
  `periodical_type_code` INT NULL,
  `language_code` INT NULL,
  `genre_code` INT NULL,
  `summary` VARCHAR(1000) NULL,
  `publisher` VARCHAR(50) NULL,
  `publication_date` DATE NULL,
  `series` VARCHAR(50) NULL,
  `title` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`periodical_id`),
  UNIQUE INDEX `book_id_UNIQUE` (`periodical_id` ASC) VISIBLE,
  INDEX `periodical_type_code_idx` (`periodical_type_code` ASC) VISIBLE,
  INDEX `genre_code_idx` (`genre_code` ASC) VISIBLE,
  INDEX `language_code_idx` (`language_code` ASC) VISIBLE,
  CONSTRAINT `periodical_type_code`
    FOREIGN KEY (`periodical_type_code`)
    REFERENCES `Library_Database`.`periodical_types` (`periodical_type_code`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `genre_code`
    FOREIGN KEY (`genre_code`)
    REFERENCES `Library_Database`.`genres` (`genre_code`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `language_code`
    FOREIGN KEY (`language_code`)
    REFERENCES `Library_Database`.`languages` (`language_code`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Library_Database`.`audiovisual_media_types`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Library_Database`.`audiovisual_media_types` (
  `audiovisual_media_type_code` INT NOT NULL AUTO_INCREMENT,
  `audiovisual_media_type` VARCHAR(20) NULL,
  PRIMARY KEY (`audiovisual_media_type_code`),
  UNIQUE INDEX `language_UNIQUE` (`audiovisual_media_type` ASC) VISIBLE,
  UNIQUE INDEX `language_code_UNIQUE` (`audiovisual_media_type_code` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Library_Database`.`audiovisual_media`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Library_Database`.`audiovisual_media` (
  `audiovisual_media_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `shelf_number` INT NULL,
  `available` INT NULL,
  `on_hold` INT NULL,
  `unavailable` INT NULL,
  `audiovisual_media_type_code` INT NULL,
  `language_code` INT NULL,
  `genre_code` INT NULL,
  `summary` VARCHAR(1000) NULL,
  `publisher` VARCHAR(50) NULL,
  `publication_date` DATE NULL,
  `runtime` INT NULL,
  `title` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`audiovisual_media_id`),
  UNIQUE INDEX `book_id_UNIQUE` (`audiovisual_media_id` ASC) VISIBLE,
  INDEX `language_code_idx` (`language_code` ASC) VISIBLE,
  INDEX `genre_code_idx` (`genre_code` ASC) VISIBLE,
  INDEX `audiovisual_media_type_code_idx` (`audiovisual_media_type_code` ASC) VISIBLE,
  CONSTRAINT `genre_code`
    FOREIGN KEY (`genre_code`)
    REFERENCES `Library_Database`.`genres` (`genre_code`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `language_code`
    FOREIGN KEY (`language_code`)
    REFERENCES `Library_Database`.`languages` (`language_code`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `audiovisual_media_type_code`
    FOREIGN KEY (`audiovisual_media_type_code`)
    REFERENCES `Library_Database`.`audiovisual_media_types` (`audiovisual_media_type_code`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Library_Database`.`contributors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Library_Database`.`contributors` (
  `contributor_id` INT UNSIGNED NOT NULL,
  `audiovisual_media_id` INT UNSIGNED NOT NULL,
  `first_name` VARCHAR(20) NOT NULL,
  `last_name` VARCHAR(20) NOT NULL,
  `role` VARCHAR(20) NULL,
  PRIMARY KEY (`contributor_id`, `audiovisual_media_id`),
  INDEX `audiovisual_media_id_idx` (`audiovisual_media_id` ASC) VISIBLE,
  CONSTRAINT `audiovisual_media_id`
    FOREIGN KEY (`audiovisual_media_id`)
    REFERENCES `Library_Database`.`audiovisual_media` (`audiovisual_media_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Library_Database`.`equipment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Library_Database`.`equipment` (
  `equipment_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `available` INT NULL,
  `on_hold` INT NULL,
  `unavailable` INT NULL,
  `equipment_name` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`equipment_id`),
  UNIQUE INDEX `equipment_id_UNIQUE` (`equipment_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Library_Database`.`patron_roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Library_Database`.`patron_roles` (
  `patron_role_code` INT NOT NULL,
  `patron_role` VARCHAR(15) NULL,
  PRIMARY KEY (`patron_role_code`),
  UNIQUE INDEX `staff_role_UNIQUE` (`patron_role` ASC) VISIBLE,
  UNIQUE INDEX `staff_role_code_UNIQUE` (`patron_role_code` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Library_Database`.`patrons`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Library_Database`.`patrons` (
  `patron_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `patron_role_code` INT NOT NULL,
  `first_name` VARCHAR(20) NOT NULL,
  `last_name` VARCHAR(20) NOT NULL,
  `date_of_birth` DATE NULL,
  `email` VARCHAR(40) NOT NULL,
  PRIMARY KEY (`patron_id`),
  UNIQUE INDEX `patron_id_UNIQUE` (`patron_id` ASC) VISIBLE,
  INDEX `patron_role_code_idx` (`patron_role_code` ASC) VISIBLE,
  CONSTRAINT `patron_role_code`
    FOREIGN KEY (`patron_role_code`)
    REFERENCES `Library_Database`.`patron_roles` (`patron_role_code`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Library_Database`.`staff_roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Library_Database`.`staff_roles` (
  `staff_role_code` INT NOT NULL,
  `staff_role` VARCHAR(15) NULL,
  PRIMARY KEY (`staff_role_code`),
  UNIQUE INDEX `staff_role_UNIQUE` (`staff_role` ASC) VISIBLE,
  UNIQUE INDEX `staff_role_code_UNIQUE` (`staff_role_code` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Library_Database`.`staff`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Library_Database`.`staff` (
  `staff_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `staff_role_code` INT NOT NULL,
  `first_name` VARCHAR(20) NOT NULL,
  `last_name` VARCHAR(20) NOT NULL,
  `date_of_birth` DATE NOT NULL,
  `email` VARCHAR(40) NOT NULL,
  `phone_number` INT NULL,
  `address` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`staff_id`),
  UNIQUE INDEX `patron_id_UNIQUE` (`staff_id` ASC) VISIBLE,
  INDEX `staff_role_code_idx` (`staff_role_code` ASC) VISIBLE,
  CONSTRAINT `staff_role_code`
    FOREIGN KEY (`staff_role_code`)
    REFERENCES `Library_Database`.`staff_roles` (`staff_role_code`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Library_Database`.`book_loans`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Library_Database`.`book_loans` (
  `patron_id` INT UNSIGNED NOT NULL,
  `book_id` INT UNSIGNED NOT NULL,
  `loan_start_date` VARCHAR(45) NOT NULL,
  `loan_return_date` VARCHAR(45) NULL,
  `loan_due_date` VARCHAR(45) NOT NULL,
  `item_type` VARCHAR(45) NULL,
  PRIMARY KEY (`patron_id`, `book_id`),
  INDEX `book_id_idx` (`book_id` ASC) VISIBLE,
  CONSTRAINT `patron_id`
    FOREIGN KEY (`patron_id`)
    REFERENCES `Library_Database`.`patrons` (`patron_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `book_id`
    FOREIGN KEY (`book_id`)
    REFERENCES `Library_Database`.`books` (`book_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Library_Database`.`fines`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Library_Database`.`fines` (
  `fine_id` INT NOT NULL AUTO_INCREMENT,
  `patron_id` INT UNSIGNED NOT NULL,
  `fine_amount` FLOAT NULL,
  `fine_date` DATE NULL,
  `paid_date` DATE NULL,
  `waived_date` DATE NULL,
  PRIMARY KEY (`fine_id`, `patron_id`),
  UNIQUE INDEX `fine_id_UNIQUE` (`fine_id` ASC) VISIBLE,
  INDEX `patron_id_idx` (`patron_id` ASC) VISIBLE,
  CONSTRAINT `patron_id`
    FOREIGN KEY (`patron_id`)
    REFERENCES `Library_Database`.`patrons` (`patron_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Library_Database`.`audiovisual_media_loans`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Library_Database`.`audiovisual_media_loans` (
  `patron_id` INT UNSIGNED NOT NULL,
  `audiovisual_media_id` INT UNSIGNED NOT NULL,
  `loan_start_date` VARCHAR(45) NOT NULL,
  `loan_return_date` VARCHAR(45) NULL,
  `loan_due_date` VARCHAR(45) NOT NULL,
  `item_type` VARCHAR(45) NULL,
  PRIMARY KEY (`patron_id`, `audiovisual_media_id`),
  INDEX `audiovisual_media_id_idx` (`audiovisual_media_id` ASC) VISIBLE,
  CONSTRAINT `patron_id`
    FOREIGN KEY (`patron_id`)
    REFERENCES `Library_Database`.`patrons` (`patron_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `audiovisual_media_id`
    FOREIGN KEY (`audiovisual_media_id`)
    REFERENCES `Library_Database`.`audiovisual_media` (`audiovisual_media_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Library_Database`.`equipment_loans`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Library_Database`.`equipment_loans` (
  `patron_id` INT UNSIGNED NOT NULL,
  `equipment_id` INT UNSIGNED NOT NULL,
  `loan_start_date` VARCHAR(45) NOT NULL,
  `loan_return_date` VARCHAR(45) NULL,
  `loan_due_date` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`patron_id`, `equipment_id`),
  INDEX `equipment_id_idx` (`equipment_id` ASC) VISIBLE,
  CONSTRAINT `patron_id`
    FOREIGN KEY (`patron_id`)
    REFERENCES `Library_Database`.`patrons` (`patron_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `equipment_id`
    FOREIGN KEY (`equipment_id`)
    REFERENCES `Library_Database`.`equipment` (`equipment_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Library_Database`.`audiovisual_media_copy1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Library_Database`.`audiovisual_media_copy1` (
  `item_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `shelf_number` INT NULL,
  `available` INT NULL,
  `on_hold` INT NULL,
  `unavailable` INT NULL,
  `media_type_code` INT NULL,
  `language_code` INT NULL,
  `genre_code` INT NULL,
  `summary` VARCHAR(1000) NULL,
  `publisher` VARCHAR(50) NULL,
  `publication_date` DATE NULL,
  `title` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`item_id`),
  UNIQUE INDEX `book_id_UNIQUE` (`item_id` ASC) VISIBLE,
  INDEX `language_code_idx` (`language_code` ASC) VISIBLE,
  INDEX `genre_code_idx` (`genre_code` ASC) VISIBLE,
  INDEX `audiovisual_media_type_code_idx` (`media_type_code` ASC) VISIBLE,
  CONSTRAINT `genre_code`
    FOREIGN KEY (`genre_code`)
    REFERENCES `Library_Database`.`genres` (`genre_code`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `language_code`
    FOREIGN KEY (`language_code`)
    REFERENCES `Library_Database`.`languages` (`language_code`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `audiovisual_media_type_code`
    FOREIGN KEY (`media_type_code`)
    REFERENCES `Library_Database`.`audiovisual_media_types` (`audiovisual_media_type_code`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Library_Database`.`equipment_holds`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Library_Database`.`equipment_holds` (
  `patron_id` INT UNSIGNED NOT NULL,
  `equipment_id` INT UNSIGNED NOT NULL,
  `hold_request_date` DATE NOT NULL,
  `priority` INT NULL,
  PRIMARY KEY (`patron_id`, `equipment_id`),
  INDEX `equipment_id_idx` (`equipment_id` ASC) VISIBLE,
  CONSTRAINT `patron_id`
    FOREIGN KEY (`patron_id`)
    REFERENCES `Library_Database`.`patrons` (`patron_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `equipment_id`
    FOREIGN KEY (`equipment_id`)
    REFERENCES `Library_Database`.`equipment` (`equipment_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
